openapi: 3.0.0
info:
  title: Parent Tearch Remote API
  version: 1.0.0
paths:
  /api/nouns:
    post:
      operationId: createNoun
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                name:
                  type: string
                image:
                  type: string
                  format: binary
            required:
              - name
              - image
      responses:
        '200':
          description: OK
  /api/conferences:
    post:
      operationId: createConference
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                studentNumber:
                  type: string
                homeRoomName:
                  type: string
                nounIds:
                  type: array
                  items:
                    type: integer
                  minItems: 1
                startDate:
                  type: string
                  format: date-time
                endDate:
                  type: string
                  format: date-time
            required:
              - studentNumber
              - homeRoomName
              - nounIds
              - startDate
              - endDate
      responses:
        '200':
          description: OK
  /api/conferences/verification:
    post:
      operationId: conferenceVerification
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                studentNumber:
                  type: string
                homeRoomName:
                  type: string
                nounIds:
                  type: array
                  items:
                    type: integer
                  minItems: 1
            required:
              - studentNumber
              - homeRoomName
              - nounIds
      responses:
        '200':
          description: OK
  /api/nouns/{id}:
    put:
      operationId: updateNoun
      parameters:
        - name: id
          in: path
          description: ID of noun to update
          required: true
          schema:
            type: integer
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                name:
                  type: string
                image:
                  type: string
                  format: binary
            required:
              - name
              - image
      responses:
        '200':
          description: OK
